// University names: National Universities Commission (NUC).
// Polytechnic names: National Board for Technical Education (NBTE).
// Sources last checked: 2026-09-12.
// https://www.nuc.edu.ng/nigerian-univerisities/federal-univeristies/
// https://www.nuc.edu.ng/nigerian-univerisities/state-univerisity/
// https://www.nuc.edu.ng/nigerian-univerisities/private-univeristies/
// https://www.digitalnbte.nbte.gov.ng/Public/PUCPolytechnics

export const NIGERIAN_UNIVERSITIES = [
  "Abdulfattah Durojaiye University, Abeokuta Ogun State",
  "AbdulKadir Kure University, Minna Niger State",
  "Abdulrasaq Abubakar Toyin University, Oke-Ogba, Ganmo, Ilorin, Kwara State",
  "Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State",
  "Abia State University, Uturu",
  "Abubakar Tafawa Balewa University, Bauchi",
  "Achievers University, Owo",
  "Adamawa State University Mubi",
  "Adeche Momoh University, Igarra, Edo State",
  "Adekunle Ajasin University, Akungba",
  "Adeleke University, Ede",
  "Adeyemi Federal University of Education, Ondo",
  "Admiralty University Ibusa, Delta State",
  "Afe Babalola University, Ado-Ekiti - Ekiti State",
  "African Aviation and Aerospace University",
  "African University of Economics, FCT, Abuja",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ahman Pategi University, Kwara State",
  "Air Force Institute of Technology, Kaduna",
  "Ajayi Crowther University, Ibadan",
  "Akwa Ibom State University, Ikot Akpaden",
  "Al-Ansar University, Maiduguri, Borno",
  "Al-Bayan University, Ankpa, Kogi State",
  "Al-Hikmah University, Ilorin",
  "Al-Istiqama University, Sumaila, Kano State",
  "Al-Muhibbah Open University, Abuja",
  "Al-Qalam University, Katsina",
  "Aletheia University, Ago-Iwoye Ogun State",
  "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
  "Aliko Dangote university of Science & Technology, Wudil",
  "Alvan Ikoku Federal University of Education, Owerri, Imo State",
  "Amadeus University, Amizi, Abia State",
  "Amaj University, Kwali, Abuja",
  "Ambrose Alli University, Ekpoma",
  "American Open University, Abeokuta, Ogun State",
  "American University of Nigeria, Yola",
  "Anan University, Kwall, Plateau State",
  "Anchor University Ayobo Lagos State",
  "Arthur Jarvis University Akpoyubo Cross river State",
  "Atiba University Oyo",
  "Augustine University",
  "Ave Maria University, Piyanko, Nasarawa State",
  "Azione Verde University, Amaigbo, Imo State",
  "Azman University, Kano State",
  "Baba Ahmed University, Kano State",
  "Babcock University,Ilishan-Remo",
  "Bamidele Olumilua University of Science and Technology Ikere, Ekiti State",
  "Bauchi State University, Gadau",
  "Bayelsa Medical University",
  "Bayero University, Kano",
  "Baze University",
  "Bells University of Technology, Otta",
  "Benson Idahosa University, Benin City",
  "Benue State University of Agriculture Science and Technology, Ihugh",
  "Bingham University, New Karu",
  "Bowen University, Iwo",
  "Bridget University Mbaise, Okirika-Nweke, Imo State",
  "British Canadian University, Obufu Cross River State",
  "Caleb University, Lagos",
  "Canadian University of Nigeria, Abuja",
  "Capital City University, Kano State",
  "Caritas University, Enugu",
  "Chrisland University",
  "Christopher University Mowe",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "City University Abuja",
  "Claretian University of Nigeria, Nekede, Imo State",
  "Clifford University Owerrinta Abia State",
  "Coal City University Enugu State",
  "College of Petroleum and Energy Studies, Kaduna State",
  "Confluence University of Science and Technology Osara, Kogi",
  "Cosmopolitan University Abuja",
  "Covenant University Ota",
  "Crawford University Igbesa",
  "Crescent University",
  "Cross River University of Education and Entrepeneurship, Akampa, Cross River State",
  "David Nweze Umahi Federal University of Medical Sciences, Uburu",
  "Delta State University Abraka",
  "Delta University of Science and Technology, Ozoro",
  "Dennis Osadebe University, Asaba",
  "Dominican University Ibadan Oyo State",
  "Dominion University Ibadan, Oyo State",
  "Ebonyi State University of ICT, Science and Technology, Oferekpe, Ebonyi State",
  "Ebonyi State University, Abakaliki",
  "Edo State University, Iyamho",
  "Edusoko University, Bida, Niger State",
  "Edwin Clark University, Kaigbodo",
  "Ekiti State University",
  "Eko University of Medical and Health Sciences Ijanikin, Lagos",
  "El-Amin University, Minna, Niger State",
  "Elizade University, Ilara-Mokin",
  "Elrazi Medical University Yargaya University, Kano State",
  "Emanuel Alayande University of Education Oyo",
  "Enugu State University of Science and Technology, Enugu",
  "Eranova University, Abuja",
  "European University of Nigeria, Duboyi, FCT",
  "Euston University, Abakaliki, Ebonyi State",
  "Evangel University, Akaeze",
  "Federal University Gashua, Yobe",
  "Federal University of Agriculture and Developmental Studies, Iragbuji, Osun State",
  "Federal University of Agriculture and Technology Obio-Akpa Akwa Ibom State",
  "Federal University of Agriculture and Technology Okeho, Oyo State",
  "Federal University of Agriculture Bassam-Biri, Bayelsa",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Agriculture, Mubi",
  "Federal University of Agriculture, Zuru, Kebbi State",
  "Federal University of Allied Health Sciences, Enugu",
  "Federal University of Applied Sciences, Kachia, Kaduna State",
  "Federal University of Education Kontagora, Niger State",
  "Federal University of Education Pankshin, Plateau State",
  "Federal University of Education, Zaria, Kaduna State",
  "Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State",
  "Federal University of Health Science and Technology, Tsafe",
  "Federal University of Health Sciences Kwale, Delta State",
  "Federal University of Health Sciences, Azare, Bauchi State",
  "Federal University of Health Sciences, Ila Orangun, Osun State",
  "Federal University of Health Sciences, Katsina",
  "Federal University of Health Sciences, Otukpo, Benue State",
  "Federal University of Medicine and Medical Sciences, Abeokuta",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Science and Technology, Epe",
  "Federal University of Science and Technology, Kabo, Kano",
  "Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Babura, Jigawa State",
  "Federal University of Technology, Ikot Abasi, Akwa Ibom State",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University of Transportation Daura, Katsina",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse, Jigawa State",
  "Federal University, Dutsin-Ma, Katsina",
  "Federal University, Gusau Zamfara",
  "Federal University, Kashere, Gombe State",
  "Federal University, Lafia, Nasarawa State",
  "Federal University, Lokoja, Kogi State",
  "Federal University, Otuoke, Bayelsa",
  "Federal University, Oye-Ekiti, Ekiti State",
  "Federal University, Wukari, Taraba State",
  "First Technical University Ibadan",
  "Fountain University, Oshogbo",
  "Franco British International University, Kaduna State",
  "Gerar University of Medical Science Imope Ijebu, Ogun State",
  "Glorious Vision University, Ogwa, Edo State",
  "Godday Erewa University, Sapele, Delta State",
  "Godfrey Okoye University, Ugwuomu-Nike - Enugu State",
  "Gombe State Univeristy, Gombe",
  "Greenfield University, Kaduna",
  "Greenland University, Jalingo, Taraba State",
  "Gregory University, Uturu",
  "Hallmark University, Ijebi Itele, Ogun",
  "Havilla University, Nde-Ikom, Cross River State",
  "Hensard University, Toru-Orua, Sagbama, Bayelsa State",
  "Hezekiah University, Umudi",
  "High Flyers University, Ikere-Ekiti, Ekiti State",
  "Hillside University of Science and Technology, Okemisi, Ekiti State",
  "Huda University, Gusau, Zamfara State",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Iconic Open University, Sokoto State",
  "Igbinedion University Okada",
  "Ignatius Ajuru University of Education,Rumuolumeni",
  "Imo State University, Owerri",
  "Isaac Balami University of Aeronautics and Management, Lagos State",
  "James Hope University, Lagos, Lagos State",
  "JEFAP University, Suleja, Niger State",
  "Jewel University, Gombe state",
  "Jigawa State University of Medical and Allied Health Sciences, Majia",
  "Jimoh Babalola University, Ilorin, Kwara State",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Joseph Sarwuan Tarka University, Makurdi",
  "Kaduna State University, Kaduna",
  "Karl-Kumm University, Vom, Plateau State",
  "Kashim Ibrahim ( formerly Bornu State) University, Maiduguri",
  "Kebbi State University of Science and Technology, Aliero",
  "Kevin Eze University, Mgbowo, Enugu State",
  "Khalifa Isiyaku Rabiu University, Kano",
  "Kings University, Ode Omu",
  "Kingsley Ozumba Mbadiwe University Ogboko, Imo State",
  "Kogi State University, Kabba",
  "Kola Daisi University Ibadan, Oyo State",
  "Kwara State University of Education, Ilorin, Kwara State",
  "Kwara State University, Ilorin",
  "Kwararafa University, Wukari",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos State University of Education, Ijanikin",
  "Lagos State University of Science and Technology Ikorodu",
  "Lagos State University, Ojo",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Leadership University, Abuja, FCT",
  "Legacy University, Okija Anambra State",
  "Lens University, Ilemona, Kwara State",
  "Lighthouse University, Evbobanosa, Edo State",
  "Lux Mundi University Umuahia, Abia State",
  "Madonna University, Okija",
  "Maduka University, Ekwegbe, Enugu State",
  "Maranatha University, Lagos",
  "Margaret Lawrence University, Umunede, Delta State",
  "Maria Assumpta University Owerri, Imo State",
  "Maryam Abacha American University of Nigeria, Kano State",
  "Mcpherson University, Seriki Sotayo, Ajebo",
  "Mercy Medical University, Iwo, Ogun State",
  "Mewar International University, Masaka, Nasarawa State",
  "Michael & Cecilia Ibru University",
  "Michael Okpara University of Agricultural Umudike",
  "Millenium Crest University, Ikare Akoko, Ondo State",
  "Minaret University, Ikirun, Osun State",
  "Miva Open University, Abuja FCT",
  "Modibbo Adama University of Technology, Yola",
  "Monarch University, Iyesi-Ota, Ogun State",
  "Moshood Abiola University of Science and Technology Abeokuta",
  "Mountain Top University",
  "Mudiame University, Irrua, Edo State",
  "Muhammad Kamalud University Kwara",
  "Nasarawa State University Keffi",
  "National Open University of Nigeria, Abuja",
  "National University of Science and Technology, Abuja",
  "New City University, Ayetoro, Ogun State",
  "Newgate University, Minna, Niger State",
  "Niger Delta University Yenagoa",
  "Nigeria Police Academy Wudil",
  "Nigerian Army University Biu",
  "Nigerian British University, Asa, Abia State",
  "Nigerian Defence Academy Kaduna",
  "Nigerian Maritime University Okerenkoko, Delta State",
  "Nigerian University of Technology and Management, Apapa, Lagos State",
  "Nile University of Nigeria, Abuja",
  "Nnamdi Azikiwe University, Awka",
  "North Eastern University, Gombe",
  "Northwest University Kano",
  "NorthWest University Sokoto State",
  "Novena University, Ogume",
  "Obafemi Awolowo University,Ile-Ife",
  "Obong University, Obong Ntak",
  "Oduduwa University, Ipetumodu - Osun State",
  "Ojaja University Eiyenkorin, Kwara State",
  "Olabisi Onabanjo University, Ago Iwoye",
  "Olusegun Agagu University of Sc. & Tech., Okitipupa, Ondo",
  "Omega University Kaduna",
  "Osun State University Osogbo",
  "Owolabi University, Oke Ila Orangun",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Pan-Atlantic University, Lagos",
  "Paul University, Awka - Anambra State",
  "PeaceLand University, Enugu State",
  "Pearl University, Calabar, Cross river",
  "Peter University, Achina-Onneh Anambra State",
  "Philomath University, Kuje, Abuja",
  "Phoenix University, Agwada, Nasarawa State",
  "Plateau State University Bokkos",
  "Precious Cornerstone University, Oyo",
  "Prime University, Kuje, FCT Abuja",
  "Prince Abubakar Audu University Anyigba",
  "Rayhaan University, Kebbi",
  "Redeemer's University, Ede",
  "Regnum Medical University, Anthony, Lagos State",
  "Renaissance University, Enugu",
  "Rev. Fr. Moses Orshio Adasu (Formerly, Benue State University), Makurdi",
  "Rhema University, Obeama-Asa - Rivers State",
  "Ritman University, Ikot Ekpene, Akwa Ibom",
  "Rivers State University",
  "Saisa University of Medical Sciences and Technology, Sokoto State",
  "Salem University, Lokoja",
  "Sam Maris University, Ondo",
  "Sani Bello University, Kontagora Niger State",
  "Shanahan University Onitsha, Anambra State",
  "Shehu Shagari University of Education, Sokoto",
  "Skyline University, Kano",
  "Sokoto State University",
  "Southern Atlantic University, Uyo, Akwa Ibom State",
  "Southwestern University, Oku Owa",
  "Spiritan University, Nneochi Abia State",
  "Sports University, Idumuje, Ugboko, Delta State",
  "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
  "Sule Lamido University, Kafin Hausa, Jigawa",
  "Summit University, Offa",
  "Tai Solarin Federal University of Education, Ijagun, Ijebu Ode",
  "Tansian University, Umunya",
  "Taraba State University of Tropical Agriculture, Science, Technology and Climate Action, Gembu",
  "Taraba State University, Jalingo",
  "Tazkiyah University, Kaduna, Kaduna State",
  "The Duke Medical University, Calabar, Cross River State",
  "Thomas Adewumi University, Oko-Irese, Kwara State",
  "Tonine Iredia University of Communication, Benin City, Edo State",
  "Topfaith University, Mkpatak, Akwa Ibom State",
  "Transatlantic University of Medine and Health Sciences, Umuchukwu, Anambra State",
  "Trinity University Ogun State",
  "Umar Musa Yar' Adua University Katsina",
  "Ummah University of Nigeria, Abuja",
  "Unique Open University, Ojo, Lagos State",
  "University of Abuja, Gwagwalada",
  "University of Aeronautics and Aerospace Engineering Ezza, Ebonyi State",
  "University of Africa Toru Orua, Bayelsa State",
  "University of Agriculture and Environmental Sciences Umuagwo, Imo State",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State, Calabar",
  "University of Delta, Agbor",
  "University of Fortune, Igbotako, Ondo State",
  "University of Ibadan",
  "University of Ilesa, Osun State",
  "University of Ilorin",
  "University of Innovation, Science and Technology, Omuma, Imo State",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Maritime Studies, Oron, Akwa Ibom State",
  "University of Medical Sciences, Ondo City, Ondo State",
  "University of Mkar, Mkar",
  "University of Nigeria, Nsukka",
  "University of Offa, Kwara State",
  "University of Port-Harcourt",
  "University of Uyo",
  "University on the Niger, Umunya, Anambra state",
  "Usumanu Danfodiyo University",
  "Venite University, Iloro-Ekiti, Ekiti State",
  "Veritas University, Abuja",
  "Vision University, Ikogbo, Ogun State",
  "Wellspring University, Evbuobanosa - Edo State",
  "Wesley University Ondo",
  "West Midlands Open University, Ibadan, Oyo State",
  "Western Delta University, Oghara Delta State",
  "Westland University Iwo, Osun State",
  "Wigwe University, Isiokpo Rivers State",
  "Yobe State University, Damaturu",
  "Yusuf Maitama Sule Federal University of Education, Kano",
  "Zamfara State University",
] as const;

export const NIGERIAN_POLYTECHNICS = [
  "Abdu Gusau Polytechnic, Talata Mafara",
  "Abia State Polytechnic, Aba",
  "Abraham Adesanya Polytechnic, Ijebu-Igbo",
  "Abubakar Tatari Ali Polytechnic, Bauchi",
  "Adamawa State Polytechnic, Yola",
  "Adeseun Ogundoyin Polytechnic, Eruwa",
  "Air Force Institute of Technology (AFIT), Airforce Base, Kaduna",
  "Ajayi Polytechnic, Ara-Ekiti",
  "Akanu Ibiam Federal Polytechnic, Unwana-Afikpo",
  "Akawe Torkula Polytechnic, Makurdi",
  "Akwa Ibom State College of Arts & Science, Nung Ukim",
  "Akwa Ibom State Polytechnic, Ikot Osurua",
  "Al-Hikma Polytechnic, Karu",
  "Allover Central Polytechnic, Sango-Ota",
  "American Polytechnic, Wasimi",
  "Anambra State Polytechnic, Mgbakwu",
  "Ashi Polytechnic, Anyin,",
  "Auchi Polytechnic, Auchi",
  "Bayelsa State Polytechnic, Aleibiri, Bayelsa",
  "Bellarks Polytechnic, Kwale",
  "Benue State Polytechnic, Ugbokolo",
  "Best Solution Polytechnic, Akure",
  "Binyamu Usman Polytechnic, Hadejia",
  "Bolmor Polytechnic, Ibadan",
  "Brainfill Polytechnic, Ikot-Ekpene",
  "British Transatlantic Polytechnic, Akure",
  "Calvary Polytechnic, Owo-Oyibu, Delta State",
  "Citi Polytechnic, Abuja",
  "Coastal Polytechnic, Badagry",
  "College of Administration, Management And Technology, Potiskum",
  "College of Agriculture, Science And Technology, Gujba",
  "College of Agriculture, Science and Technology, Lafia",
  "Covenant Polytechnic, Aba",
  "Cross River Institute of Technology And Management, Ugep",
  "Crown Polytechnic, Ado-Ekiti,",
  "D.S. Adegbenro Ict Polytechnic, Itori- Ewekoro",
  "Daboss Polytechnic",
  "Delta State Maritime Polytechnic, Burutu",
  "Delta State Polytechnic, Ogwashi-Uku",
  "Delta State Polytechnic, Otefe-Oghara",
  "Delta State Polytechnic, Ozoro, Delta State (Now Delta State University of Science And Technology)",
  "Distinct Polytechnic, Ekosin",
  "Dorben Polytechnic Bwari",
  "Eastern Polytechnic, Port Harcourt",
  "Edo State Polytechnic, Usen",
  "Edward Olaseni Polytechnic, Ajowa- Akoko, Ondo State",
  "Ekiti City Polytechnic Umuooke Ekiti",
  "Ekiti State Polytecnic, Isan-Ekiti",
  "Eko City Polytechnic",
  "El-Thomp Polytechnic, Abak. Akwa-Ibom State",
  "Enugu State Polytechnic, Iwollo",
  "Enville Institute of Management and Technology, Ikeja",
  "Federal Polytechnic Ekowe",
  "Federal Polytechnic Idah",
  "Federal Polytechnic Ile-Oluji",
  "Federal Polytechnic Kabo",
  "Federal Polytechnic Kaltungo",
  "Federal Polytechnic Kaura-Namoda",
  "FEDERAL POLYTECHNIC NGODO ISUOCHI",
  "Federal Polytechnic of Oil And Gas,Bonny,",
  "Federal Polytechnic, Ado Ekiti",
  "Federal Polytechnic, Ayede",
  "Federal Polytechnic, Bali",
  "Federal Polytechnic, Bauchi",
  "Federal Polytechnic, Bida",
  "Federal Polytechnic, Damaturu",
  "Federal Polytechnic, Daura",
  "Federal Polytechnic, Ede",
  "Federal Polytechnic, Ilaro",
  "Federal Polytechnic, Monguno",
  "Federal Polytechnic, Mubi",
  "Federal Polytechnic, Nasarawa",
  "Federal Polytechnic, Nekede",
  "Federal Polytechnic, Nyak, Shendam",
  "Federal Polytechnic, offa",
  "Federal Polytechnic, Ohodo",
  "Federal Polytechnic, Oko",
  "Federal Polytechnic, Orogun,",
  "Federal Polytechnic, Ugep",
  "Federal Polytechnic, Ukana",
  "Federal Polytechnic, Wannune",
  "Fidei Polytechnic, Gboko",
  "First City Polytechnic, Abeokuta, Ogun State",
  "Foundation Polytechnic, Ikot Ekpene",
  "Gateway Polytechnic, Saapade",
  "Gboko Polytechnic, Gboko",
  "Gestric Polytechnic, Uyo, Akwa Ibom State",
  "Global Polytechnic, Benin",
  "Gloryland Polytechnic, Ankpa",
  "Gombe State Polytechnic, Bajoga",
  "GOZIE ANYACHEBELU ORAGRAM POLYTECHNIC ORAUKWU, ANAMBRA STATE",
  "Grace Polytechnic, Surulere",
  "Graceland Polytechnic, offa",
  "Grundtvig Polytechnic, Oba",
  "Harry Pass Polytechnic, Gboko",
  "Harvard Polytechnic, Ilorin",
  "Hassan Usman Katsina Polytechnic, Katshina",
  "Heritage Polytechnic, Eket",
  "Hope Polytechnic, Ikono",
  "Hussaini Adamu Federal Polytechnic, Kazaure",
  "I-Con Universal Polytechnic, Osogbo",
  "Ibadan City Polytechnic, Ibadan",
  "Ibom Metropolitan Polytchnic, Uyo",
  "Igbajo Polytechnic, Igbajo",
  "Iheachukwu Madubuike Institute of Technology, Isouchi",
  "Imo State Polytechnic, Omuma",
  "Inspire Polytechnic, Lagos",
  "Institute of Management And Technology, Enugu",
  "Intercontinental College of Technology, Makurdi, Benue State",
  "Interlink Polytechnic, Ijebu-Jesa",
  "Isa Mustapha Agwai Polytechnic, Lafia",
  "Iwo City Polytechnic, Iwo",
  "Jigawa State Polytechnic, Dutse",
  "Kaduna Polytechnic, Kaduna",
  "Kalac Crystal Polytechnic, Lekki",
  "Kano State Polytechnic, Kano",
  "Katsina Institute of Technology And Management, Katsina",
  "Kebbi State Polytechnic Dakingari",
  "Kenule Beeson Saro-Wiwa Polytechnic, Bori",
  "Kings Polytechnic, Ubiaja",
  "Kogi State Polytechnic, Lokoja",
  "Kwara State Polytechnic, Ilorin",
  "Lagos City Polytechnic, Ikeja",
  "Lagos State Polytechnic, Ikorodu (Now Lagos State University of Science and Technology)",
  "Landmark Polytechnic, Ayetoro",
  "LeadTech School of Management and Technology, Abuja, FCT",
  "Lens Polytechnic, offa",
  "Lighthouse Polytechnic, Evbuobanosa",
  "Loam Polytechnic, Ikono",
  "MADONNA COLLEGE OF HEALTH TECHNOLOGY, OLOKORO UMUAHIA",
  "Mai-Idris Alooma Polytechnic, Geidam",
  "Marist Polytechnic, Emene",
  "Maritime Academy of Nigeria, Oron",
  "Mater Dei Polytechnic, Egwuoba",
  "Minna Institute of Technology and Innovation",
  "Montgomery Polytechnic",
  "Moshood Abiola Polytechnic, Abeokuta",
  "Mustibrah College of Information Technology and Management Studies",
  "NACABS Polytechnic, Akwanga",
  "Nasarawa State College of Agriculture, Science and Technology Lafia",
  "Nation Builders Polytechnic. Asaba",
  "National Institute of Construction Technology and Management, Uromi",
  "Newland Polytechnic, Ilorin",
  "Niger State Polytechnic, Zungeru",
  "Nigerian Army College of Environmental Science and Technology, Makurdi",
  "Nigerian College of Aviation Technology, Zaria, Kaduna State",
  "NOGAK Polytechnic, Ikom",
  "Novelty Polytechnic, Kishi",
  "Nuhu Bamalli Polytechnic, Zaria",
  "Odaji Agbo Polytechnic, Ayeko Yala",
  "Oduduwa Polytechnic, Idimu",
  "Ogun State Institute of Technology, Igbesa,",
  "Ogun State Polytechnic, Ipokia (Yet To Commence Academic Activities)",
  "Osun State College of Technology, Esa ? Oke,",
  "Osun State Polytechnic, Iree",
  "Our Saviour Institute of Science, Agriculture & Technology, Enugu",
  "Oyo State College of Agriculture And Technology, Igbo-Ora",
  "Paramount Polytechnic, Ejigbo",
  "Petroleum Training Institute, Effurun Delta State",
  "Plateau State Polytechnic, Barkin-Ladi",
  "Port-Harcourt Polytechnic, Port-Harcourt",
  "Prime Polytechnic, Jida Bassa, Ajaokuta",
  "Raindrops Institute of Management and Technology Amannchi, Orsu LGA, Imo State",
  "Raindrops Institute of Management and Technology, Amannachi, Orsu LGA, Imo State",
  "Ramat Polytechnic, Maiduguri",
  "Redeemers College of Technology And Management, Mowe",
  "Renaissance Modern Polytechnic, Mbaukwu, Anambra",
  "Ronik Polytechnic, Ejigbo, Ikeja",
  "Rufus Giwa Polytechnic, Owo",
  "Saf Polytechnic, Iseyin",
  "Shaka Polytechnic, Benin City",
  "Southern Atlantic Polytechnic, Uyo",
  "Speedway Polytechnic, Osoba",
  "St. Mary Polytechnic, Kwamba, Suleja",
  "Stars Polytechnic, Ota",
  "Sure Foundation Polytechnic, Ikot-Akai",
  "Taraba State Polytechnic, Suntai",
  "Teedek Polytechnic, Ilogbo-Ekiti",
  "Temple Gate Polytechnic, Aba",
  "The Oke-Ogun Polytechnic, Saki (Tops)",
  "The Polytechnic Aran-Orin",
  "The Polytechnic, Adoka",
  "The Polytechnic, Ibadan",
  "The Polytechnic, Igbo-Owu",
  "The Polytechnic, Ile-Ife",
  "The Polytechnic, Iresi",
  "The Polytechnic, Ojoku-Offa",
  "The Polytechnic, Omuo-Ekiti",
  "The West African Polytechnic",
  "Timeon Kairos Polytechnic, Lagos",
  "Tower Polytechnic, Ibadan",
  "Trinity Polytechnic, Uyo",
  "Ultra Excellence Polytechnic, Uyo",
  "Uma Ukpai Polytechnic, Ohafia",
  "Umaru Ali Shinkafi Polytechnic, Sokoto",
  "Unique College of Management and Technology, Lagos",
  "United Polytechnic, Jos",
  "Uyo City Polytechnic, Uyo",
  "Valley View Polytechnic, Ohafia",
  "Villanova Polytechnic, Imesi-Ile",
  "Vineyard Polytechnic",
  "Waziri Umaru Federal Polytechnic, Birnin-Kebbi",
  "Westland Polytechnic, Ilobu, Osun",
  "Wolex Polytechnic, Iwo, Osun State",
  "Yaba College of Technology, Yaba",
  "Yenagoa Polytechnic",
] as const;
