export const safeRegistrationSelect = {
  id: true,
  publicReference: true,
  ticketType: true,
  firstName: true,
  lastName: true,
  email: true,
  normalizedEmail: true,
  phoneNumber: true,
  gender: true,
  maritalStatus: true,
  maritalStatusOther: true,
  residentialAddress: true,
  activityOfInterest: true,
  discoverySource: true,
  discoverySourceOther: true,
  referral: true,
  institutionName: true,
  fieldOfStudy: true,
  studentStatusConfirmed: true,
  professionalInformation: true,
  industrySector: true,
  professionalCategory: true,
  privacyConsentAt: true,
  privacyNoticeVersion: true,
  createdAt: true,
  updatedAt: true,
} as const;
